# vim: filetype=sh

# tmux auto completion
source ~/.bash_addons/tmux

# tmux save shell history for each pane
source ~/.bash_addons/tmux-save-history.sh

# git info prompt
GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_SHOW_UPSTREAM=1
GIT_PROMPT_THEME_FILE=~/.bash_addons/git-prompt-colors.sh
source ~/.bash_addons/bash-git-prompt/gitprompt.sh

# update session variables from tmux
# based on https://babushk.in/posts/renew-environment-tmux.html
if [ -n "$TMUX" ]; then 
function tmux_refresh { 
    eval $(tmux showenv -s)
} 
#declare -- PROMPT_COMMAND="${PROPMP_COMMAND};refresh"
else 
function tmux_refresh {
    true
} 
fi

# git aliases
alias glh='git log $(git rev-parse --abbrev-ref --symbolic-full-name @{u}) ^HEAD'

# man colors
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# Change bindings
# https://stackoverflow.com/questions/1030182/how-do-i-change-bash-history-completion-to-complete-whats-already-on-the-line
# ~/.bashrc
if [[ $- == *i* ]]
then
    # up/down arrows
    bind '"\e[A": history-search-backward' 
    bind '"\e[B": history-search-forward'
    
    # page up/down
    bind '"\e[5~": previous-history'
    bind '"\e[6~": next-history'
fi

# set tmux title on ssh
if [ -n "$TMUX" ]; then 
ssh() {
    tmux rename-window "$*"
    command ssh "$@"
    tmux setw automatic-rename
}
fi
